"""Shared fixtures: tmp state dir (copies of the real files), frozen clock, fake feed/Telegram/git."""

import copy
import email.message
import io
import json
import os
import shutil
import subprocess
import sys
import urllib.error
import urllib.parse

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import jobwatch  # noqa: E402

FIXTURES = os.path.join(ROOT, "tests", "fixtures")
REAL = os.path.join(FIXTURES, "real")
STATE_FILES = ("roles.json", "seen.json", "status.json", "companies.json", "manual.json")
CREDS = {"TELEGRAM_BOT_TOKEN": "123:abc", "TELEGRAM_CHAT_ID": "42"}


def read_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def write_json(path, obj):
    jobwatch.atomic_write(path, jobwatch.canonical(obj))


def snapshot(directory):
    """{file name: bytes} for every regular file in a directory (to prove nothing changed)."""
    return {n: open(os.path.join(directory, n), "rb").read() for n in sorted(os.listdir(directory))
            if os.path.isfile(os.path.join(directory, n))}


EXPECTED = read_json(os.path.join(FIXTURES, "expected.json"))
VECTORS = read_json(os.path.join(FIXTURES, "vectors.json"))
FROZEN_NOW = EXPECTED["frozen_now"]

# The fixture feed is ~400 records; only the size gates are relaxed, everything else is the default.
SMALL_FEED_CONFIG = {"feed": dict(jobwatch.DEFAULT_CONFIG["feed"], min_records=0, min_active=0)}

README_TEMPLATE = (
    "# jobwatch\n\nA pitch.\n\n"
    f"{jobwatch.HEAD_START}\n_Generated by the bot on its next run._\n{jobwatch.HEAD_END}\n\n"
    "## How it works\n\nWords.\n\n## Current roles\n\n"
    f"{jobwatch.JOBS_START}\n_Generated by the bot on its next run._\n{jobwatch.JOBS_END}\n"
)


def cfg_with(**over):
    """A Config from the defaults with top-level keys replaced (what the loader does)."""
    data = copy.deepcopy(jobwatch.DEFAULT_CONFIG)
    data.update(copy.deepcopy(over))
    return jobwatch.Config(data)


def make_record(**over):
    rec = {
        "source": "Simplify", "category": "Software", "company_name": "TikTok", "id": "00000000-0000-0000-0000-000000000001",
        "title": "Software Engineer New Grad", "active": True, "date_updated": FROZEN_NOW - 86400,
        "date_posted": FROZEN_NOW - 86400, "url": "https://example.com/job/1", "locations": ["San Jose, CA"],
        "company_url": "https://simplify.jobs/c/TikTok", "is_visible": True, "sponsorship": "Other", "degrees": ["Bachelor's"],
    }
    rec.update(over)
    return rec


def make_row(n=1, **over):
    """An active v2 roles.json row (plus `kw`, as the digest expects) with a unique id/url."""
    row = {
        "id": f"simplify:{n:08d}-0000-0000-0000-000000000000", "company": "TikTok", "title": f"Software Engineer New Grad {n}",
        "location": "San Jose, CA", "url": f"https://example.com/job/{n}", "category": "SWE", "posted": "2026-09-01",
        "date_posted": FROZEN_NOW - n * 3600, "active": True, "first_seen": FROZEN_NOW, "locations": ["San Jose, CA"],
        "region": "US", "degrees": ["Bachelor's", "Master's"], "sponsorship": "Other", "in_feed": True, "reason": None,
    }
    row.update(over)
    row.setdefault("group", jobwatch.group_key(row["company"], row["title"]))
    row.setdefault("kw", jobwatch.norm(row["company"]))
    return row


class FakeResponse:
    def __init__(self, body):
        self.body = body

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False

    def read(self):
        return self.body


class FakeHTTP:
    """Scriptable urlopen. Outcomes: "ok" | ("ok", body_bytes) | ("http", code, body_dict[, headers]) | ("raise", exc)."""

    def __init__(self):
        self.telegram = []
        self.feed = []
        self.calls = []

    def urlopen(self, req, timeout=None):
        url = req.full_url
        if "api.telegram.org" in url:
            fields = dict(urllib.parse.parse_qsl(req.data.decode()))
            self.calls.append(("telegram", fields))
            outcome = self.telegram.pop(0) if self.telegram else "ok"
        else:
            self.calls.append(("feed", url))
            outcome = self.feed.pop(0) if self.feed else ("ok", b"[]")
        if outcome == "ok":
            return FakeResponse(b'{"ok":true,"result":{}}')
        kind = outcome[0]
        if kind == "ok":
            return FakeResponse(outcome[1])
        if kind == "http":
            headers = email.message.Message()
            for k, v in (outcome[3] if len(outcome) > 3 else {}).items():
                headers[k] = str(v)
            raise urllib.error.HTTPError(url, outcome[1], f"HTTP {outcome[1]}", headers,
                                         io.BytesIO(json.dumps(outcome[2]).encode()))
        raise outcome[1]

    def telegram_texts(self):
        return [f["text"] for kind, f in self.calls if kind == "telegram"]


class FakeClock:
    def __init__(self):
        self.t = 1000.0
        self.sleeps = []

    def monotonic(self):
        return self.t

    def sleep(self, seconds):
        self.sleeps.append(seconds)
        self.t += seconds


@pytest.fixture
def http():
    return FakeHTTP()


@pytest.fixture
def clock():
    return FakeClock()


@pytest.fixture
def frozen_now():
    return FROZEN_NOW


@pytest.fixture
def bare_state_dir(tmp_path):
    """Copies of the five real state files + a README with markers; default config (no config.json)."""
    d = tmp_path / "state"
    d.mkdir()
    for name in STATE_FILES:
        shutil.copy(os.path.join(REAL, name), d / name)
    (d / "README.md").write_text(README_TEMPLATE, encoding="utf-8")
    return str(d)


@pytest.fixture
def state_dir(bare_state_dir):
    """bare_state_dir plus a config.json that relaxes only the feed size gates (fixture feed is small)."""
    write_json(os.path.join(bare_state_dir, "config.json"), SMALL_FEED_CONFIG)
    return bare_state_dir


@pytest.fixture(scope="session")
def feed_subset():
    return read_json(os.path.join(FIXTURES, "listings_subset.json"))


@pytest.fixture(scope="session")
def feed_file(tmp_path_factory, feed_subset):
    path = tmp_path_factory.mktemp("feed") / "listings_subset.json"
    write_json(str(path), feed_subset)
    return str(path)


@pytest.fixture
def bot(bare_state_dir, feed_file, http, clock):
    """bot(*flags, env=..., now=..., feed=..., state=...) -> exit code, running jobwatch.run with fakes.

    Request `state_dir` as well to get the relaxed feed-size config; `bare_state_dir` alone keeps the defaults.
    """
    def _run(*flags, env=None, now=FROZEN_NOW, feed=feed_file, state=bare_state_dir):
        argv = ["--state-dir", state, *flags]
        if feed:
            argv += ["--feed", feed]
        args = jobwatch.parse_args(argv)
        rt = jobwatch.Runtime(now=now, env=dict(env or {}), urlopen=http.urlopen, sleep=clock.sleep, monotonic=clock.monotonic)
        try:
            return jobwatch.run(args, rt)
        except jobwatch.Abort as e:
            rt.error(e.message)
            return e.code
    return _run


def git(repo, *args, env=None):
    full_env = dict(os.environ, GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@x", GIT_COMMITTER_NAME="t",
                    GIT_COMMITTER_EMAIL="t@x", **(env or {}))
    return subprocess.run(["git", *args], cwd=repo, env=full_env, capture_output=True, text=True, check=True).stdout


FAKE_GIT_T0 = 1784000000
FAKE_GIT_SNAPSHOTS = [
    {"a": {"s": "seen"}},
    {"a": {"s": "seen"}, "b": {"s": "applied"}},
    {"a": {"s": "applied"}, "b": {"s": "applied", "star": True}},
    "not json {{{",
    {"a": {"s": "interview"}, "b": {"s": "applied", "star": True}, "c": {"s": "dropped"}},
    {"a": {"s": "interview"}, "b": {"s": "applied", "star": True}, "c": {"s": "dropped"},
     "d": {"s": "applied", "t": 1, "h": [{"s": "applied", "t": 1}]}},
]


@pytest.fixture
def fake_git(tmp_path):
    """A git repo whose status.json has 6 commits (one unparsable) a day apart from FAKE_GIT_T0."""
    repo = tmp_path / "repo"
    repo.mkdir()
    git(repo, "init", "-q", "-b", "main")
    times = []
    for i, snap in enumerate(FAKE_GIT_SNAPSHOTS):
        ct = FAKE_GIT_T0 + i * 86400
        text = snap if isinstance(snap, str) else json.dumps(snap, indent=1, sort_keys=True) + "\n"
        (repo / "status.json").write_text(text, encoding="utf-8")
        git(repo, "add", "status.json")
        git(repo, "commit", "-q", "-m", f"c{i}", env={"GIT_AUTHOR_DATE": f"@{ct} +0000", "GIT_COMMITTER_DATE": f"@{ct} +0000"})
        times.append(ct)
    return str(repo), times
