import jobwatch
from conftest import README_TEMPLATE, cfg_with, make_row

CFG = cfg_with()
PAGES = "https://alanhsiu.github.io/jobwatch/"
LAST_CHANGE = 1788480000  # 2026-09-04


def rows():
    return [make_row(i) for i in range(1, 4)] + [make_row(10, company="Cerebras", category="HW", degrees=["Bachelor's"]),
                                                 make_row(20, active=False, reason="closed", in_feed=False)]


def test_head_line_replaced_only_between_markers():
    out = jobwatch.render_readme(README_TEMPLATE, rows(), CFG, PAGES, LAST_CHANGE)
    head = out.split(jobwatch.HEAD_START)[1].split(jobwatch.HEAD_END)[0]
    assert head == ("\n_4 open new-grad roles at 2 companies · list last changed 2026-09-04 · scans every ~2 h_ · "
                    f"**[Open the tracker]({PAGES})** · [Full list ↓](#current-roles) · TikTok 3 · Cerebras 1\n")
    assert out.startswith("# jobwatch\n\nA pitch.\n\n") and "## How it works\n\nWords.\n\n## Current roles" in out
    assert "_Generated by the bot on its next run._" not in out


def test_head_markers_absent_skipped():
    text = README_TEMPLATE.replace(jobwatch.HEAD_START, "").replace(jobwatch.HEAD_END, "")
    out = jobwatch.render_readme(text, rows(), CFG, PAGES, LAST_CHANGE)
    assert "open new-grad roles at" not in out and "<details" in out


def test_jobs_markers_absent_appends_at_end():
    out = jobwatch.render_readme("# jobwatch\n\nJust docs.\n", rows(), CFG, PAGES, LAST_CHANGE)
    assert out.startswith("# jobwatch\n\nJust docs.\n\n## Current roles\n\n" + jobwatch.JOBS_START + "\n<details")
    assert out.endswith("</details>\n" + jobwatch.JOBS_END + "\n")
    again = jobwatch.render_readme(out, rows(), CFG, PAGES, LAST_CHANGE)
    assert again == out


def test_details_open_when_small():
    many = [make_row(i) for i in range(1, 25)] + [make_row(100, company="Cerebras")]
    out = jobwatch.render_jobs_list(many, CFG)
    assert "<details>\n<summary>TikTok (24)</summary>" in out
    assert "<details open>\n<summary>Cerebras (1)</summary>" in out
    assert out.index("TikTok (24)") < out.index("Cerebras (1)")  # count desc, then name


def test_group_bullets_per_posting_links():
    a = make_row(1, title="ML Engineer Graduate", location="San Jose, CA", degrees=["Bachelor's"])
    b = make_row(2, title="ML Engineer Graduate (2026)", location="Seattle, WA", degrees=["Master's"])
    out = jobwatch.render_jobs_list([b, a], CFG)
    assert (f"- [ML Engineer Graduate]({a['url']}) · [2]({b['url']}) — San Jose, CA; Seattle, WA · posted "
            f"{jobwatch.iso_date(a['date_posted'])} · SWE · BS/MS") in out
    assert out.count("\n- ") == 1


def test_absolute_dates():
    out = jobwatch.render_jobs_list(rows(), CFG)
    assert "ago" not in out and "today" not in out
    assert all(f"posted {jobwatch.iso_date(r['date_posted'])}" in out for r in rows() if r["active"])


def test_hostile_chars_escaped():
    row = make_row(1, title="[Urgent] C++|Rust <script>alert(1)</script> Engineer", company="Snap <Inc> & Co",
                   url="https://example.com/job/(1) a")
    out = jobwatch.render_jobs_list([row], CFG)
    assert "<summary>Snap &lt;Inc&gt; &amp; Co (1)</summary>" in out
    assert "- [(Urgent) C++/Rust &lt;script&gt;alert(1)&lt;/script&gt; Engineer](https://example.com/job/%281%29%20a)" in out
    assert "<script>" not in out
    # Locations are rendered raw markdown otherwise, and a newline anywhere would start a new markdown block.
    row = make_row(2, company="Evil\nCorp", title="Backend\n# Engineer\tII", location="SF <img src=x> [Apply](https://evil.example)")
    out = jobwatch.render_jobs_list([row], CFG)
    assert "<summary>Evil Corp (1)</summary>" in out
    assert "- [Backend # Engineer II](https://example.com/job/2) — SF &lt;img src=x&gt; (Apply)(https://evil.example) · posted" in out
    assert "<img" not in out and "[Apply](" not in out and "\n#" not in out
    assert out.count("\n- ") == 1


def test_head_line_sanitises_company_names():
    """The head line is bare markdown (no HTML wrapper): a newline or link syntax in a feed company name must not survive."""
    row = make_row(1, company="Evil\nCorp [x](https://evil.example) <b>b</b>")
    out = jobwatch.render_readme(README_TEMPLATE, [row], CFG, PAGES, LAST_CHANGE)
    head = out.split(jobwatch.HEAD_START)[1].split(jobwatch.HEAD_END)[0]
    assert head.startswith("\n") and head.endswith("\n") and "\n" not in head.strip("\n")
    assert "Evil Corp (x)(https://evil.example) &lt;b&gt;b&lt;/b&gt; 1" in head
    assert "\n#" not in head and "[x](" not in head and "<b>" not in head


def test_head_uses_last_change_not_run_time():
    a = jobwatch.render_readme(README_TEMPLATE, rows(), CFG, PAGES, LAST_CHANGE)
    b = jobwatch.render_readme(README_TEMPLATE, rows(), CFG, PAGES, LAST_CHANGE)
    assert a == b and "list last changed 2026-09-04" in a
    c = jobwatch.render_readme(README_TEMPLATE, rows(), CFG, PAGES, None)
    assert "list last changed" not in c and "_4 open new-grad roles at 2 companies · scans every ~2 h_" in c


def test_pages_url_from_git_remote_https_and_ssh():
    for url in ("https://github.com/Alanhsiu/jobwatch.git", "https://github.com/Alanhsiu/jobwatch", "git@github.com:Alanhsiu/jobwatch.git",
                "ssh://git@github.com/Alanhsiu/jobwatch.git", " https://github.com/Alanhsiu/jobwatch/ \n"):
        assert jobwatch.parse_remote(url) == ("Alanhsiu", "jobwatch"), url
        assert jobwatch.derive_pages_url("/".join(jobwatch.parse_remote(url))) == PAGES
    assert jobwatch.parse_remote("https://gitlab.com/o/r.git") is None
    assert jobwatch.parse_remote(None) is None


def test_user_site_repo():
    assert jobwatch.derive_pages_url("Alanhsiu/alanhsiu.github.io") == "https://alanhsiu.github.io/"
    assert jobwatch.derive_pages_url("Alanhsiu/Alanhsiu.github.io") == "https://alanhsiu.github.io/"


def test_repo_identity_sources(tmp_path):
    env = {"GITHUB_REPOSITORY": "Alanhsiu/jobwatch", "GITHUB_REF_NAME": "main"}
    assert jobwatch.repo_identity(CFG, env, str(tmp_path)) == ("Alanhsiu/jobwatch", "main", PAGES)
    assert jobwatch.repo_identity(cfg_with(pages_url="https://jobs.example.com/"), env, str(tmp_path))[2] == "https://jobs.example.com/"
    repo, branch, pages = jobwatch.repo_identity(CFG, {}, str(tmp_path))  # not a git repo
    assert repo is None and pages is None


def test_never_downgrades_existing_link():
    first = jobwatch.render_readme(README_TEMPLATE, rows(), CFG, PAGES, LAST_CHANGE)
    local = jobwatch.render_readme(first, rows(), CFG, None, LAST_CHANGE)
    assert local == first
    fresh = jobwatch.render_readme(README_TEMPLATE, rows(), CFG, None, LAST_CHANGE)
    assert "Open the tracker" not in fresh and "[Full list ↓](#current-roles)" in fresh
